[project]
name = "youtube-saas-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.120.4",
    "pydantic>=2.12.3",
    "uvicorn>=0.38.0",
    "youtube-transcript-api>=1.2.3",
]
